# Generated by Django 5.2.8 on 2025-11-28 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_offeredbook_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='offered_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='books.offeredbook'),
        ),
        migrations.AlterField(
            model_name='offeredbook',
            name='reserved',
            field=models.BooleanField(default=False, help_text='Used to mark that this book is reserved for a not yet fulfilled exchange.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, help_text='Miscelaneous notes to be displayed on the user public profile and on exchange requests.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alternate_contact',
            field=models.CharField(blank=True, help_text='Some alternative means of contact for exchanging books, e.g. WhatsApp phone number.', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_email',
            field=models.EmailField(help_text='The email the user wants to share with others when sending an exchange request.', max_length=254),
        ),
    ]
