# Generated by Django 5.2.8 on 2025-11-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_exchangerequest_offered_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredbook',
            name='author_normalized',
            field=models.CharField(db_index=True, default='placeholder', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offeredbook',
            name='title_normalized',
            field=models.CharField(db_index=True, default='placeholder', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wantedbook',
            name='author_normalized',
            field=models.CharField(db_index=True, default='placeholder', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wantedbook',
            name='title_normalized',
            field=models.CharField(db_index=True, default='placeholder', max_length=200),
            preserve_default=False,
        ),
    ]
