# Generated by Django 5.2.8 on 2025-12-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_offeredbook_author_normalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='area',
            field=models.CharField(choices=[('CABA_CENTRO', 'CABA Centro'), ('CABA_SUR', 'CABA Sur'), ('CABA_NORTE', 'CABA Norte'), ('GBA_NORTE', 'GBA Norte'), ('GBA_OESTE', 'GBA Oeste'), ('GBA_SUR', 'GBA Sur')], max_length=20),
        ),
    ]
