# Generated by Django 5.2.8 on 2025-12-02 17:25

from django.db import migrations


def convert_caba_to_caba_centro(apps, schema_editor):
    """Convert existing CABA locations to CABA_CENTRO"""
    UserLocation = apps.get_model('books', 'UserLocation')
    UserLocation.objects.filter(area='CABA').update(area='CABA_CENTRO')


def reverse_convert_caba(apps, schema_editor):
    """Reverse: Convert CABA_CENTRO back to CABA"""
    UserLocation = apps.get_model('books', 'UserLocation')
    UserLocation.objects.filter(area='CABA_CENTRO').update(area='CABA')


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_userlocation_area'),
    ]

    operations = [
        migrations.RunPython(convert_caba_to_caba_centro, reverse_convert_caba),
    ]
