# Generated by Django 5.2.8 on 2025-12-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_convert_caba_to_caba_centro'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredbook',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='User-uploaded photo of the physical book', null=True, upload_to='book_covers/%Y/%m/'),
        ),
    ]
