# Generated by Django 5.2.8 on 2025-12-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_offeredbook_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredbook',
            name='cover_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When the cover photo was last uploaded', null=True),
        ),
    ]
