# Generated by Django 5.2.8 on 2025-12-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_tempbookcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredbook',
            name='notes',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, help_text='Miscelaneous notes to be displayed on the user public profile and on exchange requests.', max_length=200),
        ),
    ]
