# Generated by Django 5.2.8 on 2025-12-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_offeredbook_notes_alter_userprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedbook',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
