# Generated by Django 5.2.8 on 2026-01-17 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_wantedbook_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredbook',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('RESERVED', 'Reserved'), ('DELETED', 'Deleted'), ('TRADED', 'Traded')], default='NEW', help_text='Current status of the book offer', max_length=20),
        ),
        migrations.AddField(
            model_name='offeredbook',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the status was last changed'),
        ),
    ]
