# Generated by Django 5.2.8 on 2025-12-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_wantedbook_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='filter_my_locations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='filter_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='filter_wanted',
            field=models.BooleanField(default=False),
        ),
    ]
