# Generated by Django 5.2.8 on 2026-02-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredbook',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TempBookCover',
        ),
    ]
